include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    always_use_package_imports: true
    avoid_returning_null: true
    prefer_single_quotes: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_const_literals_to_create_immutables: true

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    unnecessary_cast: error
    duplicate_import: error
    constant_identifier_names: ignore
